-- Migración de seguridad para Placeta Junior.
-- Ejecutar en Supabase con una clave privada distinta de la de ejemplo.
create extension if not exists pgcrypto;

alter table if exists junior_menores add column if not exists tutor_dni_hash text;
create index if not exists junior_menores_tutor_dni_hash_idx on junior_menores(tutor_dni_hash);

-- Solo para instalaciones que todavía tengan tutor_dip en claro. Sustituye
-- 'CAMBIAR-ESTA-CLAVE' por DNI_HASH_SECRET y elimina tutor_dip después.
update junior_menores
set tutor_dni_hash = encode(hmac(upper(regexp_replace(tutor_dip, '\s+', '', 'g')), 'CAMBIAR-ESTA-CLAVE', 'sha256'), 'hex')
where tutor_dni_hash is null and tutor_dip is not null;

-- El backend nuevo no necesita esta columna y nunca la debe leer:
-- alter table junior_menores drop column tutor_dip;

create table if not exists junior_reto_intentos (
  id bigint generated by default as identity primary key,
  actividad_id text not null,
  junior_id uuid not null,
  puntos_verdes integer not null default 0,
  puntos_rojos integer not null default 0,
  tiempo_ms integer not null default 0,
  creado_en timestamptz not null default now()
);
create index if not exists junior_reto_intentos_actividad_idx on junior_reto_intentos(actividad_id, creado_en);

create table if not exists junior_documentos_firmados (
  id text primary key,
  dip_menor text not null,
  junior_id text not null,
  documento_id text not null,
  version text not null,
  texto text not null,
  tutor_nombre text,
  firmado_en timestamptz not null default now()
);
create unique index if not exists junior_documentos_firmados_doc_idx on junior_documentos_firmados(dip_menor, documento_id);
